pipeline {
    agent any
    
    tools {
        maven 'Apache Maven 3.9.1' 
    }

    stages {
        stage('Maven build') {
            steps {
                script{
                    sh 'mvn clean install'
                }
            }
        }
        stage('Docker build') {
            steps{
                script {
                    imageName=docker.build("octopops24/oaes:latest")
                }
            }
        }
        stage('Docker image push to dockerhub') {
            steps {
                script{
                    docker.withRegistry('','DockerHub'){
                    imageName.push()
                    }
                }
            }
        }
    }
}
