pipeline {
    agent any

    stages {
        stage('Maven build') {
            steps {
                script{
                    sh 'mvn clean install'
                }
            }
        }
        stage('Docker build') {
            steps{
                script {
                    imageName=docker.build("octopops24/oaes:latest")
                }
            }
        }
        stage('Docker image push to dockerhub') {
            steps {
                script{
                    docker.withRegistry('','DockerHub'){
                    imageName.push()
                    }
                }
            }
        }
    }
}
